WWW/radio_ga_ga/config/routes.rb
RadioGaGa::Application.routes.draw do
  resources :searches

   root :to => 'searches#index'

end

WWW/radio_ga_ga/app/models/search.rb
class Search < ActiveRecord::Base
end

WWW/radio_ga_ga/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

WWW/radio_ga_ga/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, :notice => 'Search was successfully created.' }
        format.json { render :json => @search, :status => :created, :location => @search }
      else
        format.html { render :action => "new" }
        format.json { render :json => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to @search, :notice => 'Search was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :ok }
    end
  end
end

WWW/radio_ga_ga/app/helpers/application_helper.rb
module ApplicationHelper
end

WWW/radio_ga_ga/app/helpers/searches_helper.rb
module SearchesHelper
end

WWW/radio_ga_ga/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>RadioGaGa</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<meta name="author" content="Luka Cvrk (www.solucija.com)" />
	<meta http-equiv="content-type" content="text/html;charset=iso-8859-2" />
</head>
<body>
	<div class="content">
		<div class="header_right">
			<div class="top_info">
				<div class="top_info_right">
					<p><b>You are not Logged in!</b> <a href="#">Log in</a>  or <a href="#">register</a> to start downloading music!</p>					
				</div>		
			</div>
					
			<div class="bar">
				<ul>
					<li class="slogan">Search Categories:</li>
					<li><a href="#" accesskey="b">Bands</a></li>
					<li><a href="#" accesskey="a">Artists</a></li>
					<li class="active">Music</li>
					<li><a href="#" accesskey="p">Pictures</a></li>
					<li><a href="#" accesskey="g">Gigs</a></li>
				
				</ul>
			</div>
		</div>
			
		<div class="logo">
			<h1><a href="#" title="The best music on the net!">Internet <span class="red">Music</span></a></h1>
			<p>What shall we play today?</p>
		</div>
		
		<div class="search_field">
			<form method="post" action="?">
				<p><span class="grey">Search Example:</span> <span class="search">Progressive Trance</span>&nbsp;&nbsp; <input type="text" name="search" class="search" /> <input type="submit" value="Play!" class="button" /></p>
			</form>
		</div>
		
		<div class="newsletter">
			<p>Subscribe for Newsletter!</p>
		</div>
		
		<div class="subheader">
			<p><a href="#">Lorem ipsum dolor</a> sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex.</p>
		</div>
    <%= yield -%>		

		<div class="right">
			<div class="rt"></div>
			<div class="right_articles">
				<p><img src="assets/image.gif" alt="Image" title="Image" class="image" /><b>Lorem ipsum dolor sit amet</b><br />consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam <a href="#">erat volutpat</a>. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis <a href="#">nisl ut aliquip ex</a>.</p>
			</div>
			<div class="rt"></div>
			<div class="right_articles">
				<p><img src="assets/image.gif" alt="Image" title="Image" class="image" /><b>Lorem ipsum dolor sit amet</b><br />consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam <a href="#">erat volutpat</a>. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis <a href="#">nisl ut aliquip ex</a>.</p>
			</div>
			<div class="rt"></div>
			<div class="right_articles">
				<p><img src="assets/image.gif" alt="Image" title="Image" class="image" /><b>Lorem ipsum dolor sit amet</b><br />consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam <a href="#">erat volutpat</a>. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis <a href="#">nisl ut aliquip ex</a>.</p>
			</div>
		</div>	
		<div class="footer">
			<p><a href="#">RSS Feed</a> | <a href="#">Contact</a> | <a href="#">Accessibility</a> | <a href="#">Products</a> | <a href="#">Disclaimer</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> and <a href="http://validator.w3.org/check?uri=referer">XHTML</a><br />
			&copy; Copyright 2006 Internet Music, Design: Luka Cvrk - <a href="http://www.solucija.com/" title="What's your solution?">Solucija</a></p>
		</div>
	</div>
</body>
</html>

WWW/radio_ga_ga/app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

WWW/radio_ga_ga/app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

WWW/radio_ga_ga/app/views/searches/index.html.erb
<div class="left">
  <div class="left_articles">
    <h2><a href="#">Eurodance TOP 10</a></h2>
    <p><a href="#">Lorem ipsum dolor sit amet</a>, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. <a href="#">Ut wisi enim ad minim veniam</a>, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex.</p>
    <p><a href="#">Lorem ipsum dolor sit amet</a>, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. <a href="#">Ut wisi enim ad minim veniam</a>, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex.</p>
  </div>
        
  <div class="lt"></div>
  <div class="lbox">
    <h2>Featured Artist: <span class="yellow">Sonia</span></h2>
    <div class="thumb">
      <img src="assets/sonia.jpg" alt="" />
      <p><img src="assets/play.gif" alt="Play" /> Sonia</p>
    </div>
      
    <p>Sonia, a Croatian dance and trance artist released a number of quality tunes which rely on strong rhythm and heavy riffs.</p>
    <p>We suggest downloading and listening a dance track called <a href="http://www.solucija.com/Sonia_-_Last_night.mp3">Last Night</a></p>
  </div>
            
  <div class="lt"></div>
  <div class="lbox">
  <h2>Featured Artist: <span class="yellow">Andreas Viklund</span></h2>
  
  <div class="thumb">
  <img src="assets/andreas.jpg" alt="" />
  <p><img src="assets/play.gif" alt="Play" /> Andreas Viklund</p>
  </div>
  
  
  <p><a href="http://andreasviklund.com">Andreas Viklund</a>, a music producer from northern Sweden released a number of great songs under his own name and participated in making several <a href="http://en.wikipedia.org/wiki/Lagoona">Lagoona</a> dance and techno albums along with Björn Karlsson.</p>
  <p>We strongly suggest you listen to the song <a href="http://andreasviklund.com/music/lagoona/">Into my dream (Kaveh Azizi rmx)</a></p>
  
  </div>
</div>	

WWW/radio_ga_ga/app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

WWW/radio_ga_ga/app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>